name: Publish to Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Worker URL substitution'
        run: |
          sed -i "s|<WORKER_URL>|${{ secrets.WORKER_URL }}|g" index.js
          mkdir _site
          cp index.* p2pcf.js _site/

      - name: Fix permissions
        run: |
          chmod -c -R +rX "_site/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: 'Bundle into Pages artifact'
        uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: 'Publish from artifact'
        id: deployment
        uses: actions/deploy-pages@v4

